import { saveBodyMeasurements, saveHealthMetrics } from "./actions";
import { SectionHeading } from "@/components/section-heading";
import { dateInTimeZone } from "@/lib/date";
import { createClient } from "@/lib/supabase/server";

type Health = { id: string; measured_on: string; weight_kg: number | null; body_fat_percent: number | null; resting_heart_rate: number | null; vo2_max: number | null; steps: number | null; active_calories: number | null; total_calories: number | null; sleep_minutes: number | null; notes: string | null };
type Measurement = { id: string; measured_on: string; waist_cm: number | null; chest_cm: number | null; arm_cm: number | null; thigh_cm: number | null; hip_cm: number | null };

function shortDate(date: string) {
  return new Intl.DateTimeFormat("es-ES", { day: "numeric", month: "short" }).format(new Date(`${date}T12:00:00Z`));
}

export default async function HealthPage() {
  const supabase = await createClient();
  const today = dateInTimeZone(new Date());
  const [{ data: healthData }, { data: measurementData }] = await Promise.all([
    supabase.from("health_metrics").select("id,measured_on,weight_kg,body_fat_percent,resting_heart_rate,vo2_max,steps,active_calories,total_calories,sleep_minutes,notes").order("measured_on", { ascending: false }).limit(14),
    supabase.from("body_measurements").select("id,measured_on,waist_cm,chest_cm,arm_cm,thigh_cm,hip_cm").order("measured_on", { ascending: false }).limit(10),
  ]);
  const health = (healthData ?? []) as Health[];
  const measurements = (measurementData ?? []) as Measurement[];
  return (
    <main>
      <SectionHeading eyebrow="Registro diario" title="Salud" />
      <details className="card p-5" open={health.length === 0}><summary className="min-h-11 font-semibold">Registrar métricas</summary><form action={saveHealthMetrics} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Fecha<input className="field mt-2" name="measured_on" type="date" defaultValue={today} required /></label><label className="text-sm font-medium">Peso kg<input className="field mt-2" name="weight_kg" min="20" max="500" step="0.01" inputMode="decimal" type="number" /></label><label className="text-sm font-medium">Grasa estimada %<input className="field mt-2" name="body_fat_percent" min="0" max="100" step="0.1" type="number" /></label><label className="text-sm font-medium">FC en reposo<input className="field mt-2" name="resting_heart_rate" min="20" max="250" type="number" /></label><label className="text-sm font-medium">VO₂max estimado<input className="field mt-2" name="vo2_max" min="1" max="100" step="0.1" type="number" /></label><label className="text-sm font-medium">Pasos<input className="field mt-2" name="steps" min="0" type="number" /></label><label className="text-sm font-medium">Sueño (horas)<input className="field mt-2" name="sleep_hours" min="0" max="24" step="0.1" type="number" /></label><label className="text-sm font-medium">Calorías activas<input className="field mt-2" name="active_calories" min="0" type="number" /></label><label className="text-sm font-medium">Calorías totales<input className="field mt-2" name="total_calories" min="0" type="number" /></label><label className="text-sm font-medium sm:col-span-2">Notas<textarea className="field mt-2 min-h-24" name="notes" /></label><p className="text-xs leading-5 text-[var(--muted)] sm:col-span-2">La grasa corporal y el VO₂max se guardan como estimaciones. La aplicación prioriza su tendencia, no el valor aislado.</p><button className="primary-button sm:col-span-2" type="submit">Guardar métricas</button></form></details>

      <section className="mt-8"><p className="eyebrow mb-4">Registros recientes</p>{health.length ? <div className="space-y-3">{health.map((entry) => <article className="card p-5" key={entry.id}><div className="flex items-start justify-between"><div><p className="text-sm font-semibold uppercase">{shortDate(entry.measured_on)}</p>{entry.weight_kg !== null ? <p className="mt-2 text-2xl font-semibold">{entry.weight_kg} kg</p> : null}</div><div className="text-right text-xs leading-6 text-[var(--muted)]">{entry.body_fat_percent !== null ? <p>Grasa est. {entry.body_fat_percent}%</p> : null}{entry.resting_heart_rate !== null ? <p>FC reposo {entry.resting_heart_rate}</p> : null}{entry.vo2_max !== null ? <p>VO₂max est. {entry.vo2_max}</p> : null}</div></div><div className="mt-3 flex flex-wrap gap-x-4 text-xs text-[var(--muted)]">{entry.steps !== null ? <span>{entry.steps.toLocaleString("es-ES")} pasos</span> : null}{entry.sleep_minutes !== null ? <span>{(entry.sleep_minutes / 60).toFixed(1)} h sueño</span> : null}{entry.active_calories !== null ? <span>{entry.active_calories} kcal activas</span> : null}</div>{entry.notes ? <p className="mt-3 text-sm">{entry.notes}</p> : null}</article>)}</div> : <div className="card p-6 text-sm text-[var(--muted)]">Aún no hay métricas.</div>}</section>

      <section className="mt-10"><p className="eyebrow mb-4">Medidas corporales</p><details className="card p-5"><summary className="min-h-11 font-semibold">Añadir medidas</summary><form action={saveBodyMeasurements} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Fecha<input className="field mt-2" name="measured_on" type="date" defaultValue={today} required /></label>{[["waist_cm", "Cintura"], ["chest_cm", "Pecho"], ["arm_cm", "Brazo"], ["thigh_cm", "Muslo"], ["hip_cm", "Cadera"]].map(([name, label]) => <label className="text-sm font-medium" key={name}>{label} cm<input className="field mt-2" name={name} min="1" step="0.1" type="number" /></label>)}<label className="text-sm font-medium sm:col-span-2">Notas<textarea className="field mt-2 min-h-20" name="notes" /></label><p className="text-xs text-[var(--muted)] sm:col-span-2">No es necesario medirlas diariamente. Usa siempre condiciones similares.</p><button className="primary-button sm:col-span-2" type="submit">Guardar medidas</button></form></details>{measurements.length ? <div className="mt-3 space-y-3">{measurements.map((entry) => <article className="card p-5" key={entry.id}><p className="text-sm font-semibold uppercase">{shortDate(entry.measured_on)}</p><div className="mt-3 grid grid-cols-3 gap-3 text-sm">{[["Cintura", entry.waist_cm], ["Pecho", entry.chest_cm], ["Brazo", entry.arm_cm], ["Muslo", entry.thigh_cm], ["Cadera", entry.hip_cm]].map(([label, measurement]) => measurement !== null ? <div key={String(label)}><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-1 font-semibold">{measurement} cm</p></div> : null)}</div></article>)}</div> : null}</section>
    </main>
  );
}
